"""auto-vote

Revision ID: c95852df4d34
Revises: 3c930008d2e8
Create Date: 2023-07-13 17:59:10.617584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95852df4d34'
down_revision = '3c930008d2e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    #op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('products',
    #sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    #sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    #sa.PrimaryKeyConstraint('id', name='products_pkey')
    #)
    op.drop_table('votes')
    # ### end Alembic commands ###
